.circleci/config.yml, LICENSE, README.md, package.json
Added the a first test to the workflow: Linting
Closes #13
=> feat: Add CircleCI config

themes/gatsby-theme-emma/src/components/bg-image.tsx, themes/gatsby-theme-emma/src/components/footer.tsx, themes/gatsby-theme-emma/src/components/header.tsx, themes/gatsby-theme-emma/src/components/hero.tsx, themes/gatsby-theme-emma/src/components/navigation.tsx, themes/gatsby-theme-emma/src/components/project-item.tsx, themes/gatsby-theme-emma/src/index.d.ts, themes/gatsby-theme-emma/src/templates/page.tsx, themes/gatsby-theme-emma/src/templates/project.tsx, themes/gatsby-theme-emma/src/templates/projects.tsx, yarn.lock
A recent theme-ui update broke the color accessing from the theme as it now also includes the css custom properties syntax.
system-ui/theme-ui#259
Also change `css` to `sx`
=> fix(gatsby-theme-emma): Accessing theme value + sx prop

yarn.lock
=> fix(deps): Update emotion, theme-ui, gatsby

.circleci/config.yml, .gitignore, .npmignore, jest.config.js, jest/__mocks__/file-mock.js, jest/__mocks__/gatsby.js, jest/loadershim.js, package.json, plop-templates/theme/.npmignore.hbs, themes/gatsby-theme-status-dashboard/.npmignore, themes/gatsby-theme-status-dashboard/src/utils/__tests__/replace-words.ts, themes/gatsby-theme-status-dashboard/src/utils/formatters.ts, themes/gatsby-theme-status-dashboard/src/utils/replace-words.ts, tsconfig.json, yarn.lock
Fixes #11 
In the process of writing a test for `replaceWords` I realized that it didn't actually work in the case of multiple entries -- so I changed that function, too. That's what tests are for I guess 😆 	
Also removed the cypress directory from tsconfig so that types work fine for jest tests.
=> feat: Add jest

examples/cara/README.md, examples/emma/README.md, examples/status-dashboard/README.md, plop-templates/example/README.md.hbs, plop-templates/theme/README.md.hbs
Partially touches #28 	- it's a start at least. Want to get this in now, as `-core` themes will make it different and don't want to do extra work.
=> chore(*): Update READMEs

cypress/e2e/cara.ts, cypress/e2e/emma.ts, themes/gatsby-theme-cara/src/components/footer.tsx, themes/gatsby-theme-emma/src/components/footer.tsx
Split up the "Theme by LekoArts" into two links
=> fix: Modify footer links

README.md, themes/gatsby-theme-specimens/src/components/__tests__/audio.tsx, themes/gatsby-theme-specimens/src/components/__tests__/table.tsx, themes/gatsby-theme-specimens/src/components/__tests__/video.tsx, themes/gatsby-theme-specimens/src/components/audio.tsx, themes/gatsby-theme-specimens/src/components/table.tsx, themes/gatsby-theme-specimens/src/components/video.tsx, themes/gatsby-theme-specimens/src/hooks/__tests__/useColorUtils.tsx
More tests certainly needed, but it's a start :)
=> test: Some more Jest tests

.circleci/config.yml, cypress/e2e/cara.ts, cypress/e2e/emilia.ts, cypress/e2e/emma.ts, themes/gatsby-theme-cara/src/components/layout.tsx, themes/gatsby-theme-emilia/src/components/layout.tsx, themes/gatsby-theme-emma/src/components/layout.tsx
Fixes #70 
Includes tests for Theme UI toggle. Also upgrades the CircleCI image to latest Chrome version
=> chore(*): More Cypress tests

.eslintrc.js, themes/gatsby-theme-specimens/src/components/__tests__/color-row.tsx, themes/gatsby-theme-specimens/src/components/palette.tsx, yarn.lock
- Fix failing unit test
- Update @testing-library/jest-dom and /react
=> chore(deps): Update @testing-library & some @types

README.md, themes/gatsby-theme-cara/README.md, themes/gatsby-theme-emilia/README.md, themes/gatsby-theme-emma/README.md, themes/gatsby-theme-specimens/README.md, themes/gatsby-theme-status-dashboard/README.md, www/README.md
Add some links to Figma files and other general improvements
=> chore: Improve READMEs

yarn.lock
=> fix(deps): Update all dependencies

cypress/e2e/minimal-blog.ts, yarn.lock
Update dependencies + Add additional minimal-blog Cypress test for blog post that contains react-live code and code components.
=> fix(deps): Update dependencies & add tests

cypress/e2e/minimal-blog.ts, netlify.toml, themes/gatsby-theme-minimal-blog/src/components/blog.tsx, themes/gatsby-theme-minimal-blog/src/components/footer.tsx, themes/gatsby-theme-minimal-blog/src/components/header.tsx, themes/gatsby-theme-minimal-blog/src/components/page.tsx, themes/gatsby-theme-minimal-blog/src/components/post.tsx, themes/gatsby-theme-minimal-blog/src/components/tag.tsx, themes/gatsby-theme-minimal-blog/src/components/tags.tsx, themes/gatsby-theme-minimal-blog/src/components/title.tsx, yarn.lock
Fixes #203 
Changes `Heading` to `Styled.h2` in some places, replaces `Flex` components with regular DOM elements. Reason: `Flex` automatically has `margin: 0` and in development that messes up the styles.
=> fix(gatsby-theme-minimal-blog): Various fixes

themes/gatsby-theme-cara/README.md, themes/gatsby-theme-cara/gatsby-config.js
=> fix(gatsby-theme-cara): MDX option

themes/gatsby-theme-cara/src/components/project-card.tsx, themes/gatsby-theme-minimal-blog/src/components/title.tsx, themes/gatsby-theme-specimens/src/components/audio.tsx, themes/gatsby-theme-specimens/src/components/color-row.tsx, themes/gatsby-theme-specimens/src/components/color-swatch.tsx, themes/gatsby-theme-specimens/src/components/palette.tsx, themes/gatsby-theme-specimens/src/components/table.tsx, themes/gatsby-theme-specimens/src/components/video.tsx
Didn't test my sites a lot on Firefox but did that now and found some issues to fix. Also fixed some specimens as their style was messed up when the site was using a dark theme (so now e.g. explicitly defining a background color for table rows instead of relying on it being a white background).
Also removed the inverted array on palette specimen.
=> fix: Various styling issues in different browsers

yarn.lock
Update to latest Gatsby to leverage new features.
=> fix(deps): Update gatsby packages

.changeset/khaki-knives-do.md, themes/gatsby-theme-minimal-blog/src/components/homepage.tsx
Helps with issues like https://github.com/LekoArts/gatsby-themes/issues/540
=> fix(gatsby-theme-minimal-blog): Add two variants

cypress/e2e/minimal-blog.ts, examples/emilia/gatsby-config.js, examples/emma/gatsby-config.js, examples/jodie/README.md, examples/jodie/gatsby-config.js, examples/minimal-blog/README.md, examples/minimal-blog/gatsby-config.js, examples/minimal-blog/src/pages/404.jsx, themes/gatsby-theme-minimal-blog/gatsby-config.js
Adds explanation for question in https://github.com/LekoArts/gatsby-themes/discussions/639
=> chore(examples): Fonts explanations, 404 page for minimal-blog

.changeset/hip-hounds-peel.md, .changeset/moody-bats-cough.md, .changeset/new-avocados-rhyme.md, .changeset/selfish-ads-happen.md
Forgot to add changesets to:
- https://github.com/LekoArts/gatsby-themes/pull/693
- https://github.com/LekoArts/gatsby-themes/pull/687
- https://github.com/LekoArts/gatsby-themes/pull/690
- https://github.com/LekoArts/gatsby-themes/pull/685
=> forgotten changesets

.changeset/late-seas-begin.md, themes/gatsby-theme-emilia/README.md
1 . Changing the location requires change of Gatsby-config.js
2. Simply adding location: 'Berlin', or 'Paris', etc.. allows users to customize the location in the emilia template
=> chore(gatsby-theme-emilia): Update README

.changeset/happy-months-sin.md, themes/gatsby-theme-minimal-blog/src/styles/code.ts
=> feat(gatsby-theme-minimal-blog): Add golang tag to code blocks

themes/gatsby-theme-minimal-blog/README.md
The file linked to has since been renamed...
=> chore: Update broken link (#1132

.changeset/cold-camels-relax.md, .changeset/serious-dodos-move.md, examples/specimens/src/components/layout.tsx, examples/specimens/src/gatsby-plugin-theme-ui/index.ts, examples/status-dashboard/src/pages/index.tsx, examples/styleguide/src/@lekoarts/gatsby-theme-styleguide/layout.tsx, examples/styleguide/src/gatsby-plugin-theme-ui/index.js, themes/gatsby-theme-cara/src/components/layout.tsx, themes/gatsby-theme-cara/src/components/project-card.tsx, themes/gatsby-theme-cara/src/gatsby-plugin-theme-ui/index.ts, themes/gatsby-theme-emilia/src/components/layout.tsx, themes/gatsby-theme-emilia/src/gatsby-plugin-theme-ui/index.ts, themes/gatsby-theme-emma/src/components/layout.tsx, themes/gatsby-theme-emma/src/gatsby-plugin-theme-ui/index.ts, themes/gatsby-theme-graphql-playground/src/components/layout.tsx, themes/gatsby-theme-graphql-playground/src/gatsby-plugin-theme-ui/index.ts, themes/gatsby-theme-jodie/src/components/grid-item.tsx, themes/gatsby-theme-jodie/src/components/layout.tsx, themes/gatsby-theme-jodie/src/components/navigation.tsx, themes/gatsby-theme-jodie/src/gatsby-plugin-theme-ui/index.ts, themes/gatsby-theme-minimal-blog/src/components/layout.tsx, themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.ts
Remove `font-size: 18px` from some `html` elements. Also move some global styles from `<Global>` component to `styles.root` inside Theme UI config.
=> fix: Some global styles adjustments

.changeset/famous-needles-poke.md, themes/gatsby-theme-cara/src/components/footer.tsx, themes/gatsby-theme-emilia/src/components/colormode-toggle.tsx, themes/gatsby-theme-emma/src/components/header.tsx, themes/gatsby-theme-graphql-playground/src/components/colormode-toggle.tsx, themes/gatsby-theme-minimal-blog/src/components/colormode-toggle.tsx
Instead of spending time to fix it at the root (timesink), just apply the solution that works to unblock people.
Fixes https://github.com/LekoArts/gatsby-themes/issues/1152
=> fix: Color Mode Toggle working correctly
