LekoArts/gatsby-themes

themes/gatsby-theme-emma/README.md
themes/gatsby-theme-emma/gatsby-node.js
themes/gatsby-theme-emma/src/templates/projects.tsx

Previously I mentioned in the README that `projects` are mandatory for the emma theme as otherwise the query would break. Since https://github.com/gatsbyjs/gatsby/pull/16109 fixed this bug, I removed the note and added a (hopefully) helpful placeholder text when someone's project doesn't have content in the `projects` folder.

feat(gatsby-theme-emma): missing projects do not break site anymore

---

.github/workflows/publish-starters.yml

Publish the examples from this monorepo as starters to their respective starter repositories. Based on https://johno.com/publishing-gatsby-starters-from-monorepo

feat: Add GitHub action "Publish Starters"

---

themes/gatsby-theme-emma-core/gatsby-node.js
themes/gatsby-theme-emma-core/src/templates/project-query.tsx

This also fixes the bug/workaround that previously the projects were filtered by `id`, not `slug`. Also the SDL syntax is so much more readable. Thanks to Stefan! https://github.com/gatsbyjs/gatsby/issues/16890

fix(gatsby-theme-emma): Use SDL for schema customizations

---

themes/gatsby-theme-minimal-blog/src/components/code.tsx

Fixes #168
Partially reverts #167 
---
Seems like the Cypress checks didn't catch this error. In a follow-up PR a test will be added and the correct lazy loading behavior is implemented. Need to check what's the culprit there.

fix(gatsby-theme-minimal-blog): Revert lazy loading

---

themes/gatsby-theme-minimal-blog/src/components/code.tsx

Follow-up to #168 and #169 
This time the `theme` doesn't get lazy-loaded and manual tests show the site working with lazy loading + of course the bundle is smaller.

fix(gatsby-theme-minimal-blog): Re-Add lazy loading

---

themes/gatsby-theme-emma/src/components/project-info-item.tsx
themes/gatsby-theme-emma/src/components/project-info.tsx
themes/gatsby-theme-emma/src/components/project.tsx

Move the Item and generally speaking the ProjectInfo out of the project template so that it can be shadowed more easily. Before the 3 titles were hardcoded, now you can also pipe in other content into the info section (other source than frontmatter).

feat(gatsby-theme-emma): Improve shadow-ability of project template

---

examples/specimens/src/gatsby-plugin-theme-ui/components.js
examples/specimens/src/pages/index.mdx
themes/gatsby-theme-specimens/README.md
themes/gatsby-theme-specimens/src/components/fontFamily.tsx
themes/gatsby-theme-specimens/src/components/fontWeight.tsx
themes/gatsby-theme-specimens/src/components/heading.tsx

Fixes #219 
Adds the `previewText` prop to fontFamily, fontWeight, and heading component. Allows the user to overwrite the standard text (The quick brown fox jumps over the lazy dog)

feat(gatsby-theme-specimens): Add previewText prop

---

themes/gatsby-theme-emilia-core/README.md
themes/gatsby-theme-emilia-core/gatsby-node.js
themes/gatsby-theme-emilia-core/src/templates/project-query.tsx
themes/gatsby-theme-emilia-core/src/templates/projects-query.tsx
themes/gatsby-theme-emilia-core/utils/default-options.js
themes/gatsby-theme-emilia/README.md
themes/gatsby-theme-emilia/src/components/projects.tsx
themes/gatsby-theme-emma-core/README.md
themes/gatsby-theme-emma-core/gatsby-node.js
themes/gatsby-theme-emma-core/src/templates/project-query.tsx
themes/gatsby-theme-emma-core/utils/default-options.js
themes/gatsby-theme-emma/README.md
themes/gatsby-theme-minimal-blog-core/README.md
themes/gatsby-theme-minimal-blog-core/gatsby-node.js
themes/gatsby-theme-minimal-blog-core/src/templates/blog-query.tsx
themes/gatsby-theme-minimal-blog-core/src/templates/homepage-query.tsx
themes/gatsby-theme-minimal-blog-core/src/templates/post-query.tsx
themes/gatsby-theme-minimal-blog-core/src/templates/tag-query.tsx
themes/gatsby-theme-minimal-blog-core/utils/default-options.js
themes/gatsby-theme-minimal-blog/README.md

Adds a `formatString` option to
- gatsby-theme-minimal-blog-core (and hence also gatsby-theme-minimal-blog)
- gatsby-theme-emilia-core (and hence also gatsby-theme-emilia)
- gatsby-theme-emma-core (and hence also gatsby-theme-emma)
This enables an easy change of the date format in GraphQL queries without the need to shadow every file.
Fixes #273

feat: Add `formatString` option

---

themes/gatsby-theme-specimens/src/components/heading.tsx
themes/gatsby-theme-specimens/src/utils/filter-styles.ts
themes/gatsby-theme-styleguide/src/typography.tsx

Fixes #264
The filterStyles function was adding e.g. a `h3: undefined` to the object when `h3` was in the allowed array but not in the input styles.
Also some better checks in the Heading component when the styles object is completely missing or empty (e.g. when no heading styles/allowed is found)

fix: filterStyles & better checks in Heading

---

themes/gatsby-theme-minimal-blog/README.md
themes/gatsby-theme-minimal-blog/gatsby-config.js
themes/gatsby-theme-minimal-blog/src/utils/newsletterFeed.js

Fixes #290
Ideally one could just shadow the file but Gatsby doesn't allow that right now. If you just want to change the title, use `feedTitle`. If you want to use a customized feed, set `feed` to `false` and insert your own options.

fix: Allow customized RSS feed and title

---

themes/gatsby-theme-minimal-blog/src/components/post.tsx

Otherwise, when sharing a post, clicking on the rendered link always directs user to the blog frontpage

fix(gatsby-theme-minimal-blog): Add post slug to the url meta tag

---

themes/gatsby-theme-minimal-blog-core/gatsby-config.js

I added the `.md` extension to the plugin config options :)

fix(gatsby-theme-minimal-blog): add Markdown support to gatsby-plugin-mdx

---

themes/gatsby-theme-minimal-blog/package.json
themes/gatsby-theme-minimal-blog/src/components/code.tsx
themes/gatsby-theme-minimal-blog/src/types.d.ts
yarn.lock

Fixes https://github.com/LekoArts/gatsby-themes/issues/299
I initially added it as the bundle was quite bloated but since Gatsby (upstream) changed the chunk strategy a bit and it looks better now. On the flipside it removed the code blocks from the RSS feed.

fix: Remove `@loadable/component`

---

examples/styleguide/src/components/seo.jsx
themes/gatsby-theme-cara/src/components/seo.tsx
themes/gatsby-theme-emilia/src/components/seo.tsx
themes/gatsby-theme-emma/src/components/seo.tsx
themes/gatsby-theme-graphql-playground/src/components/seo.tsx
themes/gatsby-theme-minimal-blog/src/components/seo.tsx

Fixes #335 
This way people don't need to shadow the component when using `gatsby build --prefix-paths`

fix: Use withPrefix helper in SEO component

---

themes/gatsby-theme-minimal-blog-core/gatsby-node.js
themes/gatsby-theme-minimal-blog/src/components/blog-list-item.tsx
themes/gatsby-theme-minimal-blog/src/components/blog.tsx
themes/gatsby-theme-minimal-blog/src/components/homepage.tsx
themes/gatsby-theme-minimal-blog/src/components/listing.tsx
themes/gatsby-theme-minimal-blog/src/components/post.tsx
themes/gatsby-theme-minimal-blog/src/components/tag.tsx

Fixes #345
The `timeToRead` is handled in `gatsby-plugin-mdx`:
https://github.com/gatsbyjs/gatsby/blob/21d0e5b52121b2516eb97667d185e50796ec7e7b/packages/gatsby-plugin-mdx/gatsby/source-nodes.js#L254-L267
And it seems it has problems parsing only HTML. So I'll make it nullable. If you want the functionality for only HTML one could add a custom resolvers to the field on the `Post` type: https://www.gatsbyjs.org/docs/schema-customization/#createresolvers-api

fix: Allow timeToRead to be null

---

themes/gatsby-theme-minimal-blog/gatsby-config.js

Currently, build fails when using `feed: false` in `gatsby-config.js` because falsy values are not removed from the `plugins` list. This PR fix this.

fix(minimal-blog): remove falsy values from plugins list

---

themes/gatsby-theme-minimal-blog/src/components/header-external-links.tsx
themes/gatsby-theme-minimal-blog/src/components/header-title.tsx
themes/gatsby-theme-minimal-blog/src/components/header.tsx

This will help with issues like https://github.com/LekoArts/gatsby-themes/issues/386 as shadowing is easier now.

fix: Split header.tsx into more granular components

---

examples/minimal-blog/content/posts/fantastic-beasts-and-where-to-find-them/index.mdx
examples/minimal-blog/content/posts/introduction-to-defence-against-the-dark-arts/index.mdx
themes/gatsby-theme-minimal-blog/src/components/layout.tsx
themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.js

Fixes #414
Weird Safari quirk explained here: https://stackoverflow.com/questions/3226001/some-font-sizes-rendered-larger-on-safari-iphone

fix(gatsby-theme-minimal-blog): font-size on mobile iOS

---

examples/minimal-blog/content/posts/introduction-to-defence-against-the-dark-arts/index.mdx
examples/specimens/src/components/layout.js
examples/specimens/src/pages/index.mdx
examples/status-dashboard/src/pages/index.jsx
examples/styleguide/src/@lekoarts/gatsby-theme-styleguide/layout.jsx
themes/gatsby-theme-cara/src/components/layout.tsx
themes/gatsby-theme-emilia/src/components/layout.tsx
themes/gatsby-theme-emilia/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-emma/src/components/layout.tsx
themes/gatsby-theme-emma/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-graphql-playground/src/components/layout.tsx
themes/gatsby-theme-graphql-playground/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-minimal-blog/src/components/layout.tsx
themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-minimal-blog/src/styles/code.ts
themes/gatsby-theme-status-dashboard/src/components/info.tsx
themes/gatsby-theme-status-dashboard/src/gatsby-plugin-theme-ui/index.js

Add some `normalize.css` values to the themes.
Also adjust the `inline code` portion of the minimal blog theme to a more subtle style. Also increase the margins on the headings a little bit.

fix(*): Normalize CSS in themes & examples

---

themes/gatsby-theme-emilia-core/gatsby-node.js
themes/gatsby-theme-emma-core/gatsby-node.js
themes/gatsby-theme-graphql-playground/gatsby-node.js
themes/gatsby-theme-minimal-blog-core/gatsby-node.js

Creating the folders is a bit unnecessary in hindsight as the data source doesn't always have to be local files. When sourcing from a CMS these folders would be created nevertheless.
So this PR removes that functionality.

fix: remove folder creation in onPreBootstrap step

---

examples/cara/LICENSE
examples/cara/README.md
examples/cara/package.json
examples/emilia/LICENSE
examples/emilia/README.md
examples/emilia/package.json
examples/emma/LICENSE
examples/emma/README.md
examples/emma/package.json
examples/graphql-playground/LICENSE
examples/graphql-playground/README.md
examples/graphql-playground/package.json
examples/minimal-blog/LICENSE
examples/minimal-blog/README.md
examples/minimal-blog/package.json
examples/specimens/LICENSE
examples/specimens/README.md
examples/specimens/package.json
examples/status-dashboard/LICENSE
examples/status-dashboard/README.md
examples/status-dashboard/package.json
examples/styleguide/LICENSE
examples/styleguide/README.md
examples/styleguide/package.json
plop-templates/example/LICENSE.hbs
plop-templates/example/README.md.hbs
plop-templates/example/package.json.hbs

For starters the `OBSD` license makes more sense than the `MIT` license.

chore: Change starter licenses to 0BSD

---

themes/gatsby-theme-minimal-blog-core/gatsby-node.js
themes/gatsby-theme-minimal-blog-core/utils/default-options.js
themes/gatsby-theme-minimal-blog/README.md
themes/gatsby-theme-minimal-blog/src/components/code.tsx
themes/gatsby-theme-minimal-blog/src/components/copy.tsx
themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-minimal-blog/src/hooks/use-minimal-blog-config.tsx
themes/gatsby-theme-minimal-blog/src/styles/code.ts
themes/gatsby-theme-minimal-blog/src/styles/utils.ts
themes/gatsby-theme-minimal-blog/src/utils/copy-to-clipboard.ts

Adds a "Copy" button to the code blocks of gatsby-theme-minimal-blog.
Fixes #455

feat(minimal-blog): Add "Copy" button

---

themes/gatsby-theme-minimal-blog-core/utils/default-options.js
themes/gatsby-theme-minimal-blog/src/components/code.tsx
themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.js
themes/gatsby-theme-minimal-blog/src/styles/code.ts

Fixes #479 
- Adds styled scrollbars to code blocks
- Makes language and copy button stick to their positions while horizontally scrolling
- Fix default values for boolean themeOptions
- Adapt padding for code blocks that don't have a code title

fix(minimal-blog): Fix code block CSS positioning

---

.eslintrc.js
themes/gatsby-theme-emilia/src/@lekoarts/gatsby-theme-emilia-core/components/project.tsx
themes/gatsby-theme-emilia/src/@lekoarts/gatsby-theme-emilia-core/components/projects.tsx
themes/gatsby-theme-emilia/src/components/project.tsx
themes/gatsby-theme-emilia/src/components/projects.tsx
themes/gatsby-theme-emma/src/@lekoarts/gatsby-theme-emma-core/components/page.tsx
themes/gatsby-theme-emma/src/@lekoarts/gatsby-theme-emma-core/components/project.tsx
themes/gatsby-theme-emma/src/@lekoarts/gatsby-theme-emma-core/components/projects.tsx
themes/gatsby-theme-emma/src/components/page.tsx
themes/gatsby-theme-emma/src/components/project.tsx
themes/gatsby-theme-emma/src/components/projects.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/blog.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/homepage.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/page.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/post.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/tag.tsx
themes/gatsby-theme-minimal-blog/src/@lekoarts/gatsby-theme-minimal-blog-core/components/tags.tsx
themes/gatsby-theme-minimal-blog/src/components/blog.tsx
themes/gatsby-theme-minimal-blog/src/components/homepage.tsx
themes/gatsby-theme-minimal-blog/src/components/page.tsx

Fixes https://github.com/LekoArts/gatsby-themes/issues/483
I wasn't passing all page properties along to the components that the user is supposed to shadow thus leaving out things like e.g. `pageContext`. I now spread all props on the components, leaving the previous props like `posts` for example in tact as that would be a breaking change.
The TS types are a mess for this but I'll fix that in a follow-up PR.
Everything should still behave the same, only all props should be forwarded now.

fix: Pass all page props to page components

---

cypress/e2e/minimal-blog.ts
examples/minimal-blog/content/posts/curses-and-counter-courses/index.mdx
themes/gatsby-theme-minimal-blog-core/gatsby-node.js
themes/gatsby-theme-minimal-blog-core/src/templates/post-query.tsx
themes/gatsby-theme-minimal-blog/README.md
themes/gatsby-theme-minimal-blog/src/components/post.tsx
themes/gatsby-theme-minimal-blog/src/components/seo.tsx

Adds a `canonicalUrl` option to the frontmatter to set the respective meta tag to the `<head />`.
Fixes https://github.com/LekoArts/gatsby-themes/issues/493

feat(minimal-blog): Add Canonical URL support

---

themes/gatsby-theme-minimal-blog/src/styles/code.ts

- This PR is motivated by #514 - the intention is to add additional language flags for _gatsby-starter-minimal-blog_
- Languages added: PHP, Python
- Both flags have color contrasts of AA 
- Colors were chosen from the official colors of the language
- Languages were chosen by looking at a ranking of most commonly used in 2020
Resolves #514

fix(gatsby-theme-minimal-blog): Add additional language PHP & PY flags

---

cypress/e2e/minimal-blog.ts
themes/gatsby-theme-minimal-blog/src/components/blog.tsx
themes/gatsby-theme-minimal-blog/src/components/header-title.tsx
themes/gatsby-theme-minimal-blog/src/components/homepage.tsx
themes/gatsby-theme-minimal-blog/src/components/page.tsx
themes/gatsby-theme-minimal-blog/src/components/post.tsx
themes/gatsby-theme-minimal-blog/src/components/tag.tsx
themes/gatsby-theme-minimal-blog/src/components/tags.tsx
themes/gatsby-theme-minimal-blog/src/gatsby-plugin-theme-ui/index.js

From an SEO perspective it makes sense for the post title to be an H1 tag. No change to visual styling.

fix(gatsby-theme-minimal-blog): Use correct h1 on all pages

---

examples/jodie/src/components/style.css

That is to prevent horizontal scrolling on smaller screens
as discussed here 
Fixes #548

fix(jodie): Instagram - Match min px to match iphone 5s screen

---

examples/cara/README.md
examples/cara/gatsby-config.js
examples/emilia/README.md
examples/emilia/gatsby-config.js
examples/emma/README.md
examples/emma/gatsby-config.js
examples/graphql-playground/README.md
examples/graphql-playground/gatsby-config.js
examples/jodie/README.md
examples/jodie/gatsby-config.js
examples/minimal-blog/README.md
examples/minimal-blog/gatsby-config.js
examples/specimens/README.md
examples/specimens/gatsby-config.js
examples/status-dashboard/README.md
examples/status-dashboard/gatsby-config.js
examples/styleguide/README.md
examples/styleguide/gatsby-config.js

Don't use Gatsby CLI but normal `git clone` and `npm install` to show the `--legacy-peer-deps` flag.

chore: Update starter READMEs

---

.changeset/config.json
.changeset/thin-wasps-kneel.md
examples/minimal-blog/README.md
themes/gatsby-theme-minimal-blog/README.md
themes/gatsby-theme-minimal-blog/src/components/post-footer.tsx
themes/gatsby-theme-minimal-blog/src/components/post.tsx

**Feature:** The `<Post />` component now has a `<PostFooter />` component at the bottom of the page (between the end of the post content and the global footer). You can shadow this to e.g. display a comment section below a post. The component receives its data through the `post` prop which holds the same data as what `<Post />` receives.
Fixes https://github.com/LekoArts/gatsby-themes/discussions/698.

feat(gatsby-theme-minimal-blog): Add `PostFooter` component

---

.changeset/swift-plants-greet.md
themes/gatsby-theme-minimal-blog/src/components/homepage.tsx
themes/gatsby-theme-minimal-blog/src/components/list.tsx

Fixes https://github.com/LekoArts/gatsby-themes/issues/726

fix(gatsby-theme-minimal-blog): Incorrect link styling in bottom section

---

.changeset/witty-peaches-clap.md
themes/gatsby-theme-minimal-blog/src/components/layout.tsx

This change allows the theme to pass axe-core's rules:
- https://dequeuniversity.com/rules/axe/4.3/landmark-one-main?application=axeAPI
- https://dequeuniversity.com/rules/axe/4.3/region?application=axeAPI
There was already a `<header>` and `<footer>` but no `<main>`.

fix(gatsby-theme-minimal-blog): Use main landmark

---

.changeset/real-bears-allow.md
themes/gatsby-theme-cara/package.json
themes/gatsby-theme-emilia-core/package.json
themes/gatsby-theme-emilia/package.json
themes/gatsby-theme-emma-core/package.json
themes/gatsby-theme-emma/package.json
themes/gatsby-theme-graphql-playground/package.json
themes/gatsby-theme-jodie-core/package.json
themes/gatsby-theme-jodie/package.json
themes/gatsby-theme-minimal-blog-core/package.json
themes/gatsby-theme-minimal-blog/package.json
themes/gatsby-theme-specimens/package.json
themes/gatsby-theme-status-dashboard/package.json
themes/gatsby-theme-styleguide/package.json

The themes also support React 18, so updated the peerDependencies.

chore: Update peerDependencies to include React 18

---

.changeset/sixty-glasses-stare.md
themes/gatsby-theme-emilia/src/components/card.tsx

Fixes https://github.com/LekoArts/gatsby-themes/issues/983

fix(gatsby-theme-emilia): Text Align on Cards

---

.changeset/slow-panthers-taste.md
packages/themes-utils/src/__tests__/index.ts
packages/themes-utils/src/index.ts

Fixes https://github.com/LekoArts/gatsby-themes/issues/1017

fix(themes-utils): Change early check in preToCodeBlock

---

.changeset/serious-shirts-protect.md
themes/gatsby-theme-jodie/src/gatsby-plugin-theme-ui/index.ts

Use `img { max-width: "100%" }` on custom pages
Fixes https://github.com/LekoArts/gatsby-themes/issues/1153

fix(gatsby-theme-jodie): Correct CSS for `<img>` on custom pages

---

.changeset/short-pans-guess.md
themes/gatsby-theme-jodie-core/utils/default-options.mjs

Replacing logical or with the nullish coalescing operator allows 0 to be picked from the themeOptions, and wont be overridden by the provided default.
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing

fix(jodie-core): Allow `0` for `homepagePageLimit` and `homepageProjectLimit`
